### ISSUE TITLE
no word details anymore

### ISSUE THREAD

**Issue by rinaldi6109** [ningfei/Google-Translator-Tooltip-Expanded#10]
With the last version the script has resumed to work.
However, it seems to me that the translation panel content is no more as it was before.
Before, below the translated text, there are detailed translations, with synonims, of the main words and expressions in the selected text. Such details formed the most appreciated added value of the script.
Now, there is no such details. There is only a single translation item, which repeats the translation of selected text.
Is it possible to restore the previous script behaviour?

**Comment by ningfei** [comment]
Fixed in  fc8658f

**Comment by rinaldi6109** [comment]
It seems to me that something is wrong...
http://imgur.com/a/LKJm7

**Comment by ningfei** [comment]
@rinaldi6109  That's not wrong but showing you the alternative translations. You can turn that off in the option now. You may also want to turn off showing synonyms in the option.
