### ISSUE TITLE
更新后点击朗读无反应

### ISSUE THREAD

**Issue by wavierwister** [ningfei/Google-Translator-Tooltip-Expanded#2]
作者你好，Google Translator Tooltip Expanded Fork Third.user.js 更新后点击朗读按钮无反应。可否帮忙定位一下问题？谢谢！很棒的脚本，很稀饭~~  `(_∩_∩_)′

**Comment by ningfei** [comment]
现在应该好了。今天修复的时候大意了，抱歉。
